CREATE TABLE humans (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL
);


CREATE TABLE crysis (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cause_human_id int NOT NULL,
	start_date date,
	finish_date date,
	FOREIGN KEY (cause_human_id) REFERENCES humans(id) 
		ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE travellers (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	human_id int NOT NULL, 
	skill smallint NOT NULL DEFAULT 0
		CONSTRAINT skill_ch CHECK (skill >= 0 AND skill <= 255),
	FOREIGN KEY (human_id) REFERENCES humans(id) 
		ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE places (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL
);

CREATE TABLE journeys (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	place_id int NOT NULL,
	traveller_id int NOT NULL,
	FOREIGN KEY (place_id) REFERENCES places(id) 
		ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (traveller_id) REFERENCES travellers(id) 
		ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE journey_meetings (
	journey_id int NOT NULL,
	human_id int NOT NULL,
	FOREIGN KEY (journey_id) REFERENCES journeys(id),
	FOREIGN KEY (human_id) REFERENCES humans(id),
	CONSTRAINT journey_human_ak UNIQUE (journey_id, human_id)
);

CREATE TABLE politics (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL,
	active boolean NOT NULL DEFAULT false
);

CREATE TABLE facts (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL UNIQUE,
	utility smallint NOT NULL DEFAULT 0
		CONSTRAINT utility_ch CHECK (utility >= 0 AND utility <= 255)
);

CREATE TABLE human_facts (
	human_id int NOT NULL,
	fact_id int NOT NULL,
	FOREIGN KEY (human_id) REFERENCES humans(id),
	FOREIGN KEY (fact_id) REFERENCES facts(id),
	CONSTRAINT human_fact_ak UNIQUE (human_id, fact_id)
);

CREATE TABLE politic_facts (
	politic_id int NOT NULL,
	fact_id int NOT NULL,
	FOREIGN KEY (politic_id) REFERENCES politics(id),
	FOREIGN KEY (fact_id) REFERENCES facts(id),
	CONSTRAINT politic_fact_ak UNIQUE (politic_id, fact_id)
);

CREATE TABLE talk_tensions (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL UNIQUE
);

CREATE TABLE interviews (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	journey_id int NOT NULL,
	asker_id int NOT NULL,
	traveller_id int NOT NULL,
	talk_tension_id int,
	content text,
	FOREIGN KEY (journey_id) REFERENCES journeys(id),
	FOREIGN KEY (asker_id) REFERENCES humans(id),
	FOREIGN KEY (traveller_id) REFERENCES travellers(id),
	FOREIGN KEY (talk_tension_id) REFERENCES talk_tensions(id)
);

CREATE TABLE fears (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL UNIQUE
);

CREATE TABLE human_fears (
	human_id int NOT NULL,
	fear_id int NOT NULL,
	FOREIGN KEY (human_id) REFERENCES humans(id),
	FOREIGN KEY (fear_id) REFERENCES fears(id),
	CONSTRAINT human_fear_ak UNIQUE (human_id, fear_id)
);

CREATE TABLE interview_fears (
	interview_id int NOT NULL,
	fear_id int NOT NULL,
	FOREIGN KEY (interview_id) REFERENCES interviews(id),
	FOREIGN KEY (fear_id) REFERENCES fears(id),
	CONSTRAINT interview_fear_ak UNIQUE (interview_id, fear_id)
);
